### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by lexoyo** [hmajoros/openspace#14]
Hi
When I run `pip install -r requirements.txt` I have an error like 

```
Collecting mysql-connector-python==2.0.2 (from -r requirements.txt (line 14))
  Could not find a version that satisfies the requirement mysql-connector-python==2.0.2 (from -r requirements.txt (line 14)) (from versions: )
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external mysql-connector-python to allow).
No matching distribution found for mysql-connector-python==2.0.2 (from -r requirements.txt (line 14))
```

and then if I do `pip install -r requirements.txt --allow-external mysql-connector-python` it gives

```
Collecting mysql-connector-python==2.0.2 (from -r requirements.txt (line 14))
  HTTP error 404 while getting http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-2.0.2.zip#md5=fc07f0309d1545317d82c49593548d7f (from https://pypi.python.org/simple/mysql-connector-python/)
  Could not install requirement mysql-connector-python==2.0.2 from http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-2.0.2.zip#md5=fc07f0309d1545317d82c49593548d7f (from -r requirements.txt (line 14)) because of error 404 Client Error: Not Found
Could not install requirement mysql-connector-python==2.0.2 from http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-2.0.2.zip#md5=fc07f0309d1545317d82c49593548d7f (from -r requirements.txt (line 14)) because of HTTP error 404 Client Error: Not Found for URL http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-2.0.2.zip#md5=fc07f0309d1545317d82c49593548d7f (from https://pypi.python.org/simple/mysql-connector-python/)
```

Then I update python to version 3

```
Intermedia:openspace lexa$ sudo pip install -r requirements.txt
The directory '/Users/lexa/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/lexa/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting Django==1.4.1 (from -r requirements.txt (line 1))
  Downloading Django-1.4.1.tar.gz (7.7MB)
    100% |████████████████████████████████| 7.7MB 62kB/s 
Collecting Flask==0.10.1 (from -r requirements.txt (line 2))
  Downloading Flask-0.10.1.tar.gz (544kB)
    100% |████████████████████████████████| 544kB 381kB/s 
Collecting Flask-Login==0.2.11 (from -r requirements.txt (line 3))
  Downloading Flask-Login-0.2.11.tar.gz
Collecting Flask-SQLAlchemy==2.0 (from -r requirements.txt (line 4))
  Downloading Flask-SQLAlchemy-2.0.tar.gz (93kB)
    100% |████████████████████████████████| 94kB 814kB/s 
Collecting Jinja2==2.7.3 (from -r requirements.txt (line 5))
  Downloading Jinja2-2.7.3.tar.gz (378kB)
    100% |████████████████████████████████| 380kB 1.4MB/s 
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 6))
  Downloading MarkupSafe-0.23.tar.gz
Collecting MySQL-python==1.2.3 (from -r requirements.txt (line 7))
  Downloading MySQL-python-1.2.3.tar.gz (70kB)
    100% |████████████████████████████████| 73kB 740kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-rq10m781/MySQL-python/setup.py", line 11, in <module>
        from setup_posix import get_config
      File "/private/tmp/pip-build-rq10m781/MySQL-python/setup_posix.py", line 101
        print """You shouldn't be running this directly; it is used by setup.py."""
                                                                                  ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-rq10m781/MySQL-python
```

**Comment by kylejfrost** [comment]
_Just so you're aware, this project is super broken in its current state_

**Comment by lexoyo** [comment]
:-1: you should make it clear in the readme
I like the name and the pitch though
